### PR TITLE
Handle the case of empty events vec in event repository

### LINKED ISSUE #8: Service error when returning an empty events vec
Hi,

First of all, thanks for the excellent framework - it looks great and we're just trying to use it in one of our (internal) production services.

However, I'm getting a `service error` when I'm trying to return no events in an aggregate handler. In particular I have a handler like this:

```
    async fn handle(
        &self,
        command: Self::Command,
        _services: &Self::Services,
    ) -> Result<Vec<Self::Event>, Self::Error> {
        match command {
            S3ImageCommand::ArchiveImageDetails {} => match self {
...
            },
            S3ImageCommand::SaveImageDetails { details } => match self {
                S3Image::Initial => Ok(vec![S3ImageEvent::ImageDetailsCreated { details }]),
                S3Image::Present {
                    details: existing_details,
                } => {
                    if details == existing_details.clone() {
                        Ok(vec![]) // Idempotency
                    } else {
                        Ok(vec![S3ImageEvent::ImageDetailsUpdated { details }])
                    }
                }
...
```

and when the line
` Ok(vec![]) // Idempotency`
is called, I'm getting a Service error in production.

However, if `  Ok(vec![S3ImageEvent::ImageDetailsUpdated { details }])` is returned, the event is inserted fine.

I tried quickly to make a failing test for you in a fork, but I couldn't get your tests to run locally - I'm getting errors of the form `message: Some("The Access Key ID or security token is invalid."), ` when I fork this repo and run the tests locally.

Any help with this would be much appreciated, or if you could give me some guidance on how to get the tests working then I can potentially try and help out with this, if it's a genuine bug and not something I've overlooked on my end.

### PR DESCRIPTION
**Pull request by oco-adam**
fixes #8

### CODE REVIEW

File: tests/lib.rs [hunk 1]
```diff
@@ -84,6 +84,14 @@ async fn simple_es_commit_and_load_test(
...
         .unwrap();
     assert_eq!(3, event_store.load_events(id.as_str()).await.unwrap().len());
+    let context = event_store.load_aggregate(id.as_str()).await.unwrap();
+
+    // handle an empty events vec
+    event_store
+        .commit(vec![], context, Default::default())
+        .await
+        .unwrap();
+    assert_eq!(3, event_store.load_events(id.as_str()).await.unwrap().len());
```
Comment (davegarred) [inline tests/lib.rs:94]: This would be better as its' own test rather than appended here. E.g.,

```
#[tokio::test]
async fn commit_no_events() {
    let client = test_dynamodb_client().await;
    let repo = DynamoEventRepository::new(client);
    let event_store = PersistedEventStore::<DynamoEventRepository, Customer>::new_event_store(repo);
    let id = uuid::Uuid::new_v4().to_string();
    let context = event_store.load_aggregate(id.as_str()).await.unwrap();

    event_store
        .commit(vec![], context, Default::default())
        .await
        .unwrap();
}
```

Comment (oco-adam) [reply tests/lib.rs]: Resolved with [Moved commit_no_events to its own test](https://github.com/serverlesstechnology/dynamo-es/pull/9/commits/9941a966219c8db47706ed95648e8f6eeab23c45)

**Review by davegarred — APPROVED** [review]
